language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - composer test

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover ./code-coverage/coverage.clover
    fi